language: ruby
cache: bundler
services:
    - postgresql
before_install:
    - gem update --system
    - gem install bundler
before_script:
    - psql -c 'create database music_archive_test;' -U postgres
